// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zchhecueiqpqhvrnnmsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaGhlY3VlaXFwcWh2cm5ubXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTk1MDMsImV4cCI6MjA2MzU5NTUwM30.SWsbuGq7YflkbyUoIAah9Ap37OumXt9xlZeFe0GvxuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);